"""empty message

Revision ID: 0f42ee11d84e
Revises: a61c37a41be2
Create Date: 2017-11-30 18:52:36.242300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f42ee11d84e'
down_revision = 'a61c37a41be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ih_user_profile', ['real_name'])
    op.create_unique_constraint(None, 'ih_user_profile', ['id_card'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ih_user_profile', type_='unique')
    op.drop_constraint(None, 'ih_user_profile', type_='unique')
    # ### end Alembic commands ###
